### ISSUE TITLE
Click Filter doesn't work for the pivot

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#16]
It works In DSZ though.

Example
https://analytics.community.intersystems.com/dsw/index.html#/d/Public/Authors/Contributors2016.dashboard?ns=COMMUNITY

**Comment by ZitRos** [comment]
Please, provide additional details:

1. How to reproduce the issue.
2. What DSZ stands for?

Thanks!

**Comment by evshvarov** [comment]
1. Choose the row in the pivot with members. Two other widgets should be
filtered with the selected one.
2. DSZ=DeepSee Zen

пн, 6 февр. 2017 г. в 14:54, Nikita <notifications@github.com>:

**Comment by ZitRos** [comment]
I have updated LPT's API to make this task easier to implement in DSW. Please [update](https://github.com/intersystems-ru/LightPivotTable/releases/tag/1.7.4).

New API functions: `lpt.getRowsValues`, `lpt.getModel`, `lpt.triggers.rowClick`, `lpt.triggers.rowSelect` (see readme to see the list of arguments).

@gnibeda, instead of direct access to the LPT's data, please use `lpt.getModel` getter instead. Take note that all the data returned is mutable.

**Comment by gnibeda** [comment]
@ZitRos, Still can't get original data from server response, only converted by lpt data is accessible.
Can you provide example. how to get original data?

**Comment by ZitRos** [comment]
@gnibeda what do you mean under original data? Why returned data is not enough?

**Comment by gnibeda** [comment]
I mean original data returned by mdx2json. I already have data processor for this format, so there is no need to write converters for different cases.

**Comment by ZitRos** [comment]
Would you like to somehow intercept "original data" consumed by LPT, or you would rather like to just retrieve this data? Why can't you retrieve this data as a separate request?

If you want to retrieve that data in order to change LPT's state, this sounds a bit strange to me (and also will make the overall architecture in terms of DSW and LPT intercommunication kind of clunky).

**Comment by gnibeda** [comment]
Seems this issue is a bit outdated (2018).
Please provide an actual example.

**Comment by evshvarov** [comment]
Let’s close it

**Comment by evshvarov** [comment]
[here is the demo](https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/Bug/ClickFilter.dashboard)
Click filter works for Pie-chart. 
But if you switch to pivot it doesn't work

**Comment by gnibeda** [comment]
Done in 3.1.79
