### ISSUE TITLE
DSW cannot create the portlet because there is a "-" in the file name

### ISSUE THREAD

**Issue by gnibeda** [intersystems-community/DeepSeeWeb#174]
Need somehow fix or allow portlet creation for filenames with "-" character.
Related to: https://github.com/intersystems-community/DeepSeeWeb/issues/170#issuecomment-788875972

**Comment by eduard93** [comment]
Which MDX2JSON call are you using?

Which error are you getting?

**Comment by gnibeda** [comment]
@qou99 Can you provide information?

**Comment by qou99** [comment]
I get this error when I call the DSW Login page
![0](https://user-images.githubusercontent.com/37990393/109935782-291ff700-7cce-11eb-9c56-5d8810199bc3.jpg)
![1](https://user-images.githubusercontent.com/37990393/109935851-2d4c1480-7cce-11eb-81cf-999bf9015cf7.jpg)

A package with a hyphen in the name cannot be created in IRIS. That's why I thought maybe you could name the addon examples simpler, like htmlviewer.js

**Comment by eduard93** [comment]
Yes, please don't use anything besides A-Z, a-z 0-9 in addon names.

**Comment by gnibeda** [comment]
addons has been renamed in 3.1.4
