### ISSUE TITLE
alignment issue with numeric data in pivot table

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#264]
if data goes as 0.00 or 0.50 it aligned to left, but 0.91 aligns to right in the same col.

**Comment by Lena-Ev** [comment]
the problem is in MDX2JSON

Request:
/MDX2JSON/MDXDrillthrough?Namespace=DEMO
{"MDX":"DRILLTHROUGH SELECT FROM [PRODUCTIONPLANCUBE] %FILTER %OR({[runID].[H1].[runID].&[FF001] })"}

All the data in the shipping cost should be the same format (number)
![image](https://user-images.githubusercontent.com/77621970/199290504-20932a22-791d-4a70-8d5e-cf0e70054611.png)

**Comment by evshvarov** [comment]
It is in the Number format. This is how number format looks like

**Comment by Lena-Ev** [comment]
https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/IRISAPP/Basic%20Dashboard%20Demo.dashboard

**Comment by jakcpto** [comment]
@evshvarov @Lena-Ev 
Can we report an issue to core system methods? 
Or it is better to build workaround?

Seems like the problem goes from Class %ZEN.Auxiliary.jsonSQLProvider and %WriteJSONFromSQL method.


![Image](https://user-images.githubusercontent.com/41373877/202134433-1e4dbff3-6542-4f90-998f-a794f2463e46.png)

**Comment by Lena-Ev** [comment]
@eduard93 Could you release MDX2JSON please with this update
