### ISSUE TITLE
New design step 2 (tiles, breadcrums, menu)

### ISSUE THREAD

**Issue by Lena-Ev** [intersystems-community/DeepSeeWeb#322]
new menu button and points themselves and new beradcrumbs style:

![Image](https://user-images.githubusercontent.com/77621970/213259394-ac65adbe-bf58-42d9-8086-696da4d88d44.png)

if there is more than 3 points of crumbs we hide them with this symbol "..."
when you click on this symbol you will see the hidden points 

- [x] new style for search (it is not properly working btw) and move language and logout options there as well as the logo

![Image](https://user-images.githubusercontent.com/77621970/213259313-4fbf7ea1-9fe1-4035-a5c5-513caccd9303.png)

- [x] new tiles design - left alignment and just 2 lines for the name - the rest of the name should be visible in tooltips 

![Image](https://user-images.githubusercontent.com/77621970/213258883-008abaa8-d7df-4b12-a5ac-f957dffe1eee.png)

**Comment by gnibeda** [comment]
> search (it is not properly working btw) 
The dashboards request in mdx2json is broken.
Request: `/MDX2JSON/Dashboards?Namespace=IRISAPP`
Payload: `{"Folder":""}`
Response:
![image](https://user-images.githubusercontent.com/9804674/215581339-61fe69b3-8594-4075-8a92-b1c6c1072046.png)
Empty title on some items. Because the search is done by the title, it doesn't work. Please fix mdx2json.

**Comment by jakcpto** [comment]
@gnibeda I think that in example titles are not shown because they are empty in dashboards.
If I fill some title in according field, the response from mdx2json is quite similar to data saved in dashboard:
![image](https://user-images.githubusercontent.com/41373877/216616483-0200ccab-4435-4e67-9d97-555f81885f8a.png)
saved, then I  see
![image](https://user-images.githubusercontent.com/41373877/216616925-f031d4b3-59b6-4a12-9140-45653ccad688.png)

Also we can use Dashboard Name value in case of empty title. 
Do we need to? @Lena-Ev
