### ISSUE TITLE
Fix json by Anton's comment

### ISSUE THREAD

**Issue by Lena-Ev** [intersystems-community/DeepSeeWeb#329]
![Image](https://user-images.githubusercontent.com/77621970/215409396-af26057b-3369-4924-adc8-d498050c95b1.png)

**Comment by jakcpto** [comment]
@Lena-Ev This issue was fixed at Jan 16.

https://github.com/intersystems-ru/Cache-MDX2JSON/commit/e62a498864b0fd73ec4ba6c16e21c95e4df7beb7#diff-704e277be43ab552d90d9116debf900f7db2d060ff545b155e6e76a3d9f1bb4d

Now MDX2JSON contains necessary code:
<img width="938" alt="image" src="https://user-images.githubusercontent.com/41373877/216031843-071b6e2b-bb75-4cf8-a22c-cc4ec7f87ee9.png">

**Comment by jakcpto** [comment]
Can close
