### ISSUE TITLE
ComboChart: doesn't show series properly

### ISSUE THREAD

**Issue by v23ent** [intersystems-community/DeepSeeWeb#382]
Details: plot_type is not captured from DeepSee properly. Sequentionally applying plot_type like: bar, line, bar, line, ...
The actual sequence in plot types are: bar, bar, bar, line.

Steps to reproduce:
1. Create a combochart
2. Add 2 series of data to it
3. Make both series display as 'bar'

Example:
DSW: https://samples-bi-demo.demo.community.intersystems.com/dsw/index.html#/USER/Widget%20Examples/Combo%20Chart.dashboard
DeepSee: https://samples-bi-demo.demo.community.intersystems.com/csp/user/_DeepSee.UserPortal.DashboardViewer.zen?DASHBOARD=Widget%20Examples%2FCombo%20Chart.dashboard

Screenshots:
<img width="1498" alt="Screen Shot 2023-05-30 at 4 41 31 pm" src="https://github.com/intersystems-community/DeepSeeWeb/assets/12609489/ba50f124-e09b-41cf-b0c9-2405e7efb84f">
<img width="1474" alt="Screen Shot 2023-05-30 at 4 41 13 pm" src="https://github.com/intersystems-community/DeepSeeWeb/assets/12609489/3654b1a7-7497-4eaa-9817-cb7e28725fd2">

**Comment by gnibeda** [comment]
The issue was produced by marker type setting. If set to a third type of marker:
![image](https://github.com/intersystems-community/DeepSeeWeb/assets/9804674/ed3b9cd4-1964-428a-9bff-5f8e5f07df6b)
Then there is no type for this series:
![image](https://github.com/intersystems-community/DeepSeeWeb/assets/9804674/8c3df785-737c-413b-9223-013dd42058eb)

**Comment by evshvarov** [comment]
@v23ent  we are closing it as it seems working
