### ISSUE TITLE
Implement auditing support for DSW dashboards usages

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#430]
THis works in DSZ. Here is documentation
https://docs.intersystems.com/iris20233/csp/docbook/DocBook.UI.Page.cls?KEY=D2IMP_ch_dev#D2IMP_audit_code

Could it be implemented in DSZ as well?

**Comment by Lena-Ev** [comment]
- [ ] example @Frisle 
- [ ] add to new release PR @Frisle

**Comment by Frisle** [comment]
The logging method performed according to the documentation provided does not enable dashboard/query auditing through Audit UI. This doc. has concrete example of using console instead of Audit UI.

I will look for another way to enable it, but it will take more time to research. We need to set a deadline for completing this task. And if my research fails, I suggest writing our own version of auditing using a workaround I recently wrote 

You said you have some .xml doc from client. Could you send it to me somewhere?
